// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/testing.proto

package ws.moor.gletscher.proto.testing;

public final class Testing {
  private Testing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ws.moor.gletscher.proto.testing.File)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bytes contents = 2;</code>
     */
    com.google.protobuf.ByteString getContents();

    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMeta();
  }
  /**
   * Protobuf type {@code ws.moor.gletscher.proto.testing.File}
   */
  public  static final class File extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ws.moor.gletscher.proto.testing.File)
      FileOrBuilder {
    // Use File.newBuilder() to construct.
    private File(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private File() {
      name_ = "";
      contents_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private File(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {

              contents_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                meta_ = com.google.protobuf.MapField.newMapField(
                    MetaDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              meta = input.readMessage(
                  MetaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              meta_.getMutableMap().put(meta.getKey(), meta.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_File_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMeta();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_File_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ws.moor.gletscher.proto.testing.Testing.File.class, ws.moor.gletscher.proto.testing.Testing.File.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contents_;
    /**
     * <code>optional bytes contents = 2;</code>
     */
    public com.google.protobuf.ByteString getContents() {
      return contents_;
    }

    public static final int META_FIELD_NUMBER = 3;
    private static final class MetaDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_File_MetaEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> meta_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMeta() {
      if (meta_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDefaultEntryHolder.defaultEntry);
     }
      return meta_;
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return internalGetMeta().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!contents_.isEmpty()) {
        output.writeBytes(2, contents_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMeta().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        meta = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, meta);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!contents_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contents_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMeta().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        meta = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, meta);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ws.moor.gletscher.proto.testing.Testing.File parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ws.moor.gletscher.proto.testing.Testing.File prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ws.moor.gletscher.proto.testing.File}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ws.moor.gletscher.proto.testing.File)
        ws.moor.gletscher.proto.testing.Testing.FileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_File_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMeta();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMeta();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ws.moor.gletscher.proto.testing.Testing.File.class, ws.moor.gletscher.proto.testing.Testing.File.Builder.class);
      }

      // Construct using ws.moor.gletscher.proto.testing.Testing.File.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        contents_ = com.google.protobuf.ByteString.EMPTY;

        internalGetMutableMeta().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_File_descriptor;
      }

      public ws.moor.gletscher.proto.testing.Testing.File getDefaultInstanceForType() {
        return ws.moor.gletscher.proto.testing.Testing.File.getDefaultInstance();
      }

      public ws.moor.gletscher.proto.testing.Testing.File build() {
        ws.moor.gletscher.proto.testing.Testing.File result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ws.moor.gletscher.proto.testing.Testing.File buildPartial() {
        ws.moor.gletscher.proto.testing.Testing.File result = new ws.moor.gletscher.proto.testing.Testing.File(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.contents_ = contents_;
        result.meta_ = internalGetMeta();
        result.meta_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ws.moor.gletscher.proto.testing.Testing.File) {
          return mergeFrom((ws.moor.gletscher.proto.testing.Testing.File)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ws.moor.gletscher.proto.testing.Testing.File other) {
        if (other == ws.moor.gletscher.proto.testing.Testing.File.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getContents() != com.google.protobuf.ByteString.EMPTY) {
          setContents(other.getContents());
        }
        internalGetMutableMeta().mergeFrom(
            other.internalGetMeta());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ws.moor.gletscher.proto.testing.Testing.File parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ws.moor.gletscher.proto.testing.Testing.File) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contents_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public com.google.protobuf.ByteString getContents() {
        return contents_;
      }
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public Builder setContents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public Builder clearContents() {
        
        contents_ = getDefaultInstance().getContents();
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> meta_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMeta() {
        if (meta_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetaDefaultEntryHolder.defaultEntry);
       }
        return meta_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMeta() {
        onChanged();;
        if (meta_ == null) {
          meta_ = com.google.protobuf.MapField.newMapField(
              MetaDefaultEntryHolder.defaultEntry);
        }
        if (!meta_.isMutable()) {
          meta_ = meta_.copy();
        }
        return meta_;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getMeta() {
        return internalGetMeta().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMeta() {
        return internalGetMutableMeta().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      public Builder putAllMeta(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableMeta().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ws.moor.gletscher.proto.testing.File)
    }

    // @@protoc_insertion_point(class_scope:ws.moor.gletscher.proto.testing.File)
    private static final ws.moor.gletscher.proto.testing.Testing.File DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ws.moor.gletscher.proto.testing.Testing.File();
    }

    public static ws.moor.gletscher.proto.testing.Testing.File getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<File>
        PARSER = new com.google.protobuf.AbstractParser<File>() {
      public File parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new File(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<File> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<File> getParserForType() {
      return PARSER;
    }

    public ws.moor.gletscher.proto.testing.Testing.File getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ws.moor.gletscher.proto.testing.FileList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    java.util.List<ws.moor.gletscher.proto.testing.Testing.File> 
        getFileList();
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    ws.moor.gletscher.proto.testing.Testing.File getFile(int index);
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    int getFileCount();
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    java.util.List<? extends ws.moor.gletscher.proto.testing.Testing.FileOrBuilder> 
        getFileOrBuilderList();
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    ws.moor.gletscher.proto.testing.Testing.FileOrBuilder getFileOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ws.moor.gletscher.proto.testing.FileList}
   */
  public  static final class FileList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ws.moor.gletscher.proto.testing.FileList)
      FileListOrBuilder {
    // Use FileList.newBuilder() to construct.
    private FileList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FileList() {
      file_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FileList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                file_ = new java.util.ArrayList<ws.moor.gletscher.proto.testing.Testing.File>();
                mutable_bitField0_ |= 0x00000001;
              }
              file_.add(input.readMessage(ws.moor.gletscher.proto.testing.Testing.File.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          file_ = java.util.Collections.unmodifiableList(file_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_FileList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_FileList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ws.moor.gletscher.proto.testing.Testing.FileList.class, ws.moor.gletscher.proto.testing.Testing.FileList.Builder.class);
    }

    public static final int FILE_FIELD_NUMBER = 1;
    private java.util.List<ws.moor.gletscher.proto.testing.Testing.File> file_;
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    public java.util.List<ws.moor.gletscher.proto.testing.Testing.File> getFileList() {
      return file_;
    }
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    public java.util.List<? extends ws.moor.gletscher.proto.testing.Testing.FileOrBuilder> 
        getFileOrBuilderList() {
      return file_;
    }
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    public int getFileCount() {
      return file_.size();
    }
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    public ws.moor.gletscher.proto.testing.Testing.File getFile(int index) {
      return file_.get(index);
    }
    /**
     * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
     */
    public ws.moor.gletscher.proto.testing.Testing.FileOrBuilder getFileOrBuilder(
        int index) {
      return file_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < file_.size(); i++) {
        output.writeMessage(1, file_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < file_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, file_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ws.moor.gletscher.proto.testing.Testing.FileList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ws.moor.gletscher.proto.testing.Testing.FileList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ws.moor.gletscher.proto.testing.FileList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ws.moor.gletscher.proto.testing.FileList)
        ws.moor.gletscher.proto.testing.Testing.FileListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_FileList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_FileList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ws.moor.gletscher.proto.testing.Testing.FileList.class, ws.moor.gletscher.proto.testing.Testing.FileList.Builder.class);
      }

      // Construct using ws.moor.gletscher.proto.testing.Testing.FileList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFileFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (fileBuilder_ == null) {
          file_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fileBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ws.moor.gletscher.proto.testing.Testing.internal_static_ws_moor_gletscher_proto_testing_FileList_descriptor;
      }

      public ws.moor.gletscher.proto.testing.Testing.FileList getDefaultInstanceForType() {
        return ws.moor.gletscher.proto.testing.Testing.FileList.getDefaultInstance();
      }

      public ws.moor.gletscher.proto.testing.Testing.FileList build() {
        ws.moor.gletscher.proto.testing.Testing.FileList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ws.moor.gletscher.proto.testing.Testing.FileList buildPartial() {
        ws.moor.gletscher.proto.testing.Testing.FileList result = new ws.moor.gletscher.proto.testing.Testing.FileList(this);
        int from_bitField0_ = bitField0_;
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            file_ = java.util.Collections.unmodifiableList(file_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.file_ = file_;
        } else {
          result.file_ = fileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ws.moor.gletscher.proto.testing.Testing.FileList) {
          return mergeFrom((ws.moor.gletscher.proto.testing.Testing.FileList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ws.moor.gletscher.proto.testing.Testing.FileList other) {
        if (other == ws.moor.gletscher.proto.testing.Testing.FileList.getDefaultInstance()) return this;
        if (fileBuilder_ == null) {
          if (!other.file_.isEmpty()) {
            if (file_.isEmpty()) {
              file_ = other.file_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFileIsMutable();
              file_.addAll(other.file_);
            }
            onChanged();
          }
        } else {
          if (!other.file_.isEmpty()) {
            if (fileBuilder_.isEmpty()) {
              fileBuilder_.dispose();
              fileBuilder_ = null;
              file_ = other.file_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fileBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFileFieldBuilder() : null;
            } else {
              fileBuilder_.addAllMessages(other.file_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ws.moor.gletscher.proto.testing.Testing.FileList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ws.moor.gletscher.proto.testing.Testing.FileList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ws.moor.gletscher.proto.testing.Testing.File> file_ =
        java.util.Collections.emptyList();
      private void ensureFileIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          file_ = new java.util.ArrayList<ws.moor.gletscher.proto.testing.Testing.File>(file_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ws.moor.gletscher.proto.testing.Testing.File, ws.moor.gletscher.proto.testing.Testing.File.Builder, ws.moor.gletscher.proto.testing.Testing.FileOrBuilder> fileBuilder_;

      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public java.util.List<ws.moor.gletscher.proto.testing.Testing.File> getFileList() {
        if (fileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(file_);
        } else {
          return fileBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public int getFileCount() {
        if (fileBuilder_ == null) {
          return file_.size();
        } else {
          return fileBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public ws.moor.gletscher.proto.testing.Testing.File getFile(int index) {
        if (fileBuilder_ == null) {
          return file_.get(index);
        } else {
          return fileBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder setFile(
          int index, ws.moor.gletscher.proto.testing.Testing.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.set(index, value);
          onChanged();
        } else {
          fileBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder setFile(
          int index, ws.moor.gletscher.proto.testing.Testing.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.set(index, builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder addFile(ws.moor.gletscher.proto.testing.Testing.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.add(value);
          onChanged();
        } else {
          fileBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder addFile(
          int index, ws.moor.gletscher.proto.testing.Testing.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.add(index, value);
          onChanged();
        } else {
          fileBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder addFile(
          ws.moor.gletscher.proto.testing.Testing.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.add(builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder addFile(
          int index, ws.moor.gletscher.proto.testing.Testing.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.add(index, builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder addAllFile(
          java.lang.Iterable<? extends ws.moor.gletscher.proto.testing.Testing.File> values) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, file_);
          onChanged();
        } else {
          fileBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public Builder removeFile(int index) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.remove(index);
          onChanged();
        } else {
          fileBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public ws.moor.gletscher.proto.testing.Testing.File.Builder getFileBuilder(
          int index) {
        return getFileFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public ws.moor.gletscher.proto.testing.Testing.FileOrBuilder getFileOrBuilder(
          int index) {
        if (fileBuilder_ == null) {
          return file_.get(index);  } else {
          return fileBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public java.util.List<? extends ws.moor.gletscher.proto.testing.Testing.FileOrBuilder> 
           getFileOrBuilderList() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(file_);
        }
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public ws.moor.gletscher.proto.testing.Testing.File.Builder addFileBuilder() {
        return getFileFieldBuilder().addBuilder(
            ws.moor.gletscher.proto.testing.Testing.File.getDefaultInstance());
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public ws.moor.gletscher.proto.testing.Testing.File.Builder addFileBuilder(
          int index) {
        return getFileFieldBuilder().addBuilder(
            index, ws.moor.gletscher.proto.testing.Testing.File.getDefaultInstance());
      }
      /**
       * <code>repeated .ws.moor.gletscher.proto.testing.File file = 1;</code>
       */
      public java.util.List<ws.moor.gletscher.proto.testing.Testing.File.Builder> 
           getFileBuilderList() {
        return getFileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ws.moor.gletscher.proto.testing.Testing.File, ws.moor.gletscher.proto.testing.Testing.File.Builder, ws.moor.gletscher.proto.testing.Testing.FileOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ws.moor.gletscher.proto.testing.Testing.File, ws.moor.gletscher.proto.testing.Testing.File.Builder, ws.moor.gletscher.proto.testing.Testing.FileOrBuilder>(
                  file_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ws.moor.gletscher.proto.testing.FileList)
    }

    // @@protoc_insertion_point(class_scope:ws.moor.gletscher.proto.testing.FileList)
    private static final ws.moor.gletscher.proto.testing.Testing.FileList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ws.moor.gletscher.proto.testing.Testing.FileList();
    }

    public static ws.moor.gletscher.proto.testing.Testing.FileList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileList>
        PARSER = new com.google.protobuf.AbstractParser<FileList>() {
      public FileList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new FileList(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<FileList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileList> getParserForType() {
      return PARSER;
    }

    public ws.moor.gletscher.proto.testing.Testing.FileList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ws_moor_gletscher_proto_testing_File_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ws_moor_gletscher_proto_testing_File_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ws_moor_gletscher_proto_testing_File_MetaEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ws_moor_gletscher_proto_testing_File_MetaEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ws_moor_gletscher_proto_testing_FileList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ws_moor_gletscher_proto_testing_FileList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026src/test/testing.proto\022\037ws.moor.gletsc" +
      "her.proto.testing\"\222\001\n\004File\022\014\n\004name\030\001 \001(\t" +
      "\022\020\n\010contents\030\002 \001(\014\022=\n\004meta\030\003 \003(\0132/.ws.mo" +
      "or.gletscher.proto.testing.File.MetaEntr" +
      "y\032+\n\tMetaEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\"?\n\010FileList\0223\n\004file\030\001 \003(\0132%.ws.mo" +
      "or.gletscher.proto.testing.Fileb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ws_moor_gletscher_proto_testing_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ws_moor_gletscher_proto_testing_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ws_moor_gletscher_proto_testing_File_descriptor,
        new java.lang.String[] { "Name", "Contents", "Meta", });
    internal_static_ws_moor_gletscher_proto_testing_File_MetaEntry_descriptor =
      internal_static_ws_moor_gletscher_proto_testing_File_descriptor.getNestedTypes().get(0);
    internal_static_ws_moor_gletscher_proto_testing_File_MetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ws_moor_gletscher_proto_testing_File_MetaEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ws_moor_gletscher_proto_testing_FileList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ws_moor_gletscher_proto_testing_FileList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ws_moor_gletscher_proto_testing_FileList_descriptor,
        new java.lang.String[] { "File", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
